import type { Metadata } from "next";

import { CommandBlock } from "@/components/command-block";
import { CLI_INIT_COMMAND, CLI_PACKAGE, CLI_VERSION_TAG, cliCommand } from "@/lib/commands";

export const metadata: Metadata = {
  title: "Installation",
  description: "Prerequisites, install modes, and verification steps for first-time Harness Kit setup.",
};

export default function InstallationPage() {
  return (
    <article className="bundle-content">
      <h1>Installation</h1>
      <p>
        Global install is recommended for teams that run commands frequently across multiple repositories. Use{" "}
        <code>npx</code> if you prefer zero-maintenance upgrades or are doing a one-off setup.
      </p>
      <h2>Prerequisites</h2>
      <ul>
        <li>Node.js 18+ installed.</li>
        <li>Git repository initialized in your project.</li>
        <li>Network access for package fetch on first run.</li>
      </ul>
      <h2>Option 1: Install globally</h2>
      <CommandBlock
        label="Install CLI globally"
        variants={[
          { label: "pnpm", command: `pnpm add -g ${CLI_PACKAGE}@${CLI_VERSION_TAG}` },
          { label: "npm",  command: `npm install -g ${CLI_PACKAGE}@${CLI_VERSION_TAG}` },
          { label: "yarn", command: `yarn global add ${CLI_PACKAGE}@${CLI_VERSION_TAG}` },
        ]}
      />
      <CommandBlock command="harness-kit init" label="Initialize after global install" className="mt-3" />
      <p className="mt-2 text-sm text-muted-foreground">
        Recommended for repeated daily usage across multiple repositories.
      </p>
      <h2>Option 2: Run without global install</h2>
      <CommandBlock command={CLI_INIT_COMMAND} label="Run init immediately with npx" />
      <p className="mt-2 text-sm text-muted-foreground">
        Useful for one-off setups or when you want the newest CLI without managing global upgrades.
      </p>
      <h2>Verify setup</h2>
      <p>
        After the wizard completes, verify that harness files were generated and no baseline drift is detected.
      </p>
      <CommandBlock
        label="Check harness status"
        variants={[
          { label: "npx",    command: cliCommand("status") },
          { label: "global", command: "harness-kit status" },
        ]}
      />
      <h2>Expected artifacts after init</h2>
      <ul>
        <li>
          <code>harness.json</code> (tracked harness state).
        </li>
        <li>
          <code>CLAUDE.md</code> and <code>AGENTS.md</code> (baseline guidance).
        </li>
        <li>Bundle-specific artifacts (rules, skills, hooks, MCP config) based on your selection.</li>
      </ul>
      <h2>After installation</h2>
      <ol>
        <li>Commit the baseline generated by <code>init</code>.</li>
        <li>Add one high-value bundle (for example <code>tdd</code>).</li>
        <li>
          Run <code>status</code> again with either <code>npx</code> or your global install and commit the incremental
          diff.
        </li>
      </ol>
      <p>
        If something fails, check <strong>Troubleshooting</strong> for quick symptom-to-fix guidance.
      </p>
    </article>
  );
}
