import type { Metadata } from "next";

import { CommandBlock } from "@/components/command-block";

export const metadata: Metadata = {
  title: "Installation",
  description: "Prerequisites, install modes, and verification steps for first-time Harness Kit setup.",
};

export default function InstallationPage() {
  return (
    <article className="bundle-content">
      <h1>Installation</h1>
      <p>
        Most teams should start with <code>npx</code> for zero-maintenance upgrades. Global install is useful when you
        run commands frequently across many repositories.
      </p>
      <h2>Prerequisites</h2>
      <ul>
        <li>Node.js 18+ installed.</li>
        <li>Git repository initialized in your project.</li>
        <li>Network access for package fetch on first run.</li>
        <li>Optional: <code>pnpm</code> if you prefer global install with pnpm.</li>
      </ul>
      <h2>Option 1: Run without global install</h2>
      <CommandBlock command="npx @harness-kit/cli@latest init" label="Run init immediately" />
      <p className="mt-2 text-sm text-muted-foreground">
        Recommended for first-time setup and teams that want the newest CLI without managing global updates.
      </p>
      <h2>Option 2: Install globally</h2>
      <CommandBlock command="pnpm add -g @harness-kit/cli" label="Install CLI globally" />
      <CommandBlock command="harness-kit init" label="Initialize after global install" className="mt-3" />
      <p className="mt-2 text-sm text-muted-foreground">
        Better for repeated daily usage across multiple repositories.
      </p>
      <h2>Verify setup</h2>
      <p>
        After the wizard completes, verify that harness files were generated and no baseline drift is detected.
      </p>
      <CommandBlock command="harness-kit status" label="Check harness status" />
      <h2>Expected artifacts after init</h2>
      <ul>
        <li>
          <code>harness.json</code> (tracked harness state).
        </li>
        <li>
          <code>CLAUDE.md</code> and <code>AGENTS.md</code> (baseline guidance).
        </li>
        <li>Bundle-specific artifacts (rules, skills, hooks, MCP config) based on your selection.</li>
      </ul>
      <h2>After installation</h2>
      <ol>
        <li>Commit the baseline generated by <code>init</code>.</li>
        <li>Add one high-value bundle (for example <code>tdd</code>).</li>
        <li>Run <code>harness-kit status</code> again and commit the incremental diff.</li>
      </ol>
      <p>
        If something fails, check <strong>Troubleshooting</strong> for quick symptom-to-fix guidance.
      </p>
    </article>
  );
}
